ProBillInvoice/Controllers/Ad_UserTrackingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProBillInvoice.DAL;
using ProBillInvoice.Models;

namespace ProBillInvoice.Controllers
{
    [Authorize]
    public class Ad_UserTrackingController : Controller
    {
        // GET: UserTracking
        string currentMonth = DateTime.Now.Month.ToString();
        string currentYear = DateTime.Now.Year.ToString();
        public ActionResult Index()
        {
            string lsFromDate = string.Format("{0}-{1}-01 00:00:00.000", DateTime.Now.Year, DateTime.Now.Month);
            string lsToDate = string.Format("{0: yyyy-MM-dd 23:59:59.999}", DateTime.Now);
                        
            Ad_UserLoginTrackingModel mymodel = new Ad_UserLoginTrackingModel();
            ClsUserLoginTracking lsUserTracking = new ClsUserLoginTracking();
            mymodel.FromDate = Convert.ToDateTime(lsFromDate);
            mymodel.ToDate = Convert.ToDateTime(lsToDate);

            mymodel.UserLoginTrackingList = lsUserTracking.UserTrackingList("log_in_time between '" + lsFromDate + "' and '" + lsToDate + "'");
            return View(mymodel);
        }

        [HttpPost]
        public ActionResult Search(Ad_UserLoginTrackingModel UT)
        {
            string lsFromDate = string.Format("{0: yyyy/MM/dd 00:00:00.000}", UT.FromDate);
            string lsToDate = string.Format("{0: yyyy/MM/dd 23:59:59.999}", UT.ToDate);
                        
            string lsFilter = string.Empty;
            //if (SOM.SaleOrderHeaderSearch.PartyId != null)
            //{
            //    lsFilter = lsFilter + " sale_order_header. party_id = " + SOM.SaleOrderHeaderSearch.PartyId + " AND ";
            //}            
            lsFilter = lsFilter + "log_in_time between '" + lsFromDate + "' and '" + lsToDate + "' ";

            Ad_UserLoginTrackingModel mymodel = new Ad_UserLoginTrackingModel();
            ClsUserLoginTracking lsUserTracking = new ClsUserLoginTracking();
            mymodel.UserLoginTrackingList = lsUserTracking.UserTrackingList(lsFilter);
            return View("Index", mymodel);
        }
    }
}

ProBillInvoice/Views/Ad_UserTracking/Index.cshtml
@model ProBillInvoice.Models.Ad_UserLoginTrackingModel

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h4 class="card-title mb-0">User Tracking - Search Criteria </h4>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div style="float: left; width: 50%;">
                                                @Html.LabelFor(model => Model.FromDate, new { @class = "form-label", @style = "float: left; padding: 4px 10px 0px 0px;" })
                                                @Html.EditorFor(model => Model.FromDate, new { htmlAttributes = new { @type = "Date", @class = "form-control form-control-sm", @style = "width: 65%;" } })
                                                @Html.ValidationMessageFor(model => Model.FromDate, "", new { @class = "text-danger" })
                                            </div>
                                            <div style="float: left; width: 50%;">
                                                @Html.LabelFor(model => Model.ToDate, new { @class = "form-label", @style = "float: left; padding: 4px 10px 0px 10px;" })
                                                @Html.EditorFor(model => Model.ToDate, new { htmlAttributes = new { @type = "Date", @class = "form-control form-control-sm", @style = "width: 65%;" } })
                                                @Html.ValidationMessageFor(model => Model.ToDate, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="row">
                                        <div class="col-md-6" style="padding-top: 5px; text-align : left;">
                                            <button type="submit" class="btn btn-primary addMembers-modal" style="padding: 2px 10px 2px 10px;" formmethod="post" formaction="Search"><div style="float: left; padding: 0 5px 0 0;"><i class="ri-search-2-line"></i></div>Search</button>
                                        </div>
                                        <div class="col-md-6">
                                            @*<div class="checkbox" style="float: left; padding: 5px 10px 0px 0px;">
                @Html.EditorFor(model => model.SaleOrderHeaderSearch.order_close, new { @onclick = "myFunction(this.value);" })
                @Html.ValidationMessageFor(model => model.SaleOrderHeaderSearch.order_close, "", new { @class = "text-danger" })
            </div>
            @Html.Label("Close SO", htmlAttributes: new { @style = "float: left; padding: 3px 10px 0px 0px; margin-bottom: 0px; color: red; width: 80%;" })*@
                                        </div>

                                    </div>
                                </div>
                                <div class="col-md-4">
                                    @*<div class="row">
                <div class="col-md-3">
                    @Html.Label("Party Name", new { @class = "form-label", @style = "float: left; padding: 4px 10px 0px 0px;" })
                </div>
                <div class="col-md-9">
                    @Html.DropDownListFor(Model => Model.SaleOrderHeaderSearch.PartyId, (SelectList)ViewBag.PartyList, "-- Select--", new { @class = "form-select form-select-sm", @style = "width: 85%;" })
                </div>
            </div>*@
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <h5 class="card-title mb-0" style="font-size: 24px; padding-top: 10px;">User Tracking  View</h5>
                            </div>
                            <div class="col-sm-6" style="text-align: right;">
                                <a href="@Url.Action("Create", "Ad_UserTracking")" class="btn btn-info"><i class="las la-plus-square"></i><span><strong>Create</strong></span></a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="UserTracking" class="table table-bordered dt-responsive nowrap table-striped align-middle" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>Sr No</th>
                                            <th>User Name</th>
                                            <th>Ip Address</th>
                                            <th>Log In Datetime</th>
                                            <th>Log Out Datetime</th>
                                        </tr>
                                    </thead>

                                    @if (Model.UserLoginTrackingList != null)
                                    {                                        
                                        foreach (var item in Model.UserLoginTrackingList)
                                        {
                                    <tr>
                                        <td><a href="#!">@Html.DisplayFor(modelItem => item.sr_no)</a></td>
                                        <td>@Html.DisplayFor(modelItem => item.user_email)</td>
                                        <td>@Html.DisplayFor(modelItem => item.ip_address)</td>
                                        <td>@string.Format("{0:dd/MM/yyyy hh:mm:ss}", item.log_in_time)</td>
                                        <td>@string.Format("{0:dd/MM/yyyy hh:mm:ss}", item.log_out_time)</td>
                                    </tr>                                           
                                        }
                                    }
                                </table>
                            </div>
                        </div>
                                             
                        <fieldset style="border: 1px solid #e7dddd; border-radius: 10px; padding: 5px 10px 5px 10px;">
                            <div class="row mb-0">
                                <div class="col-sm-6">
                                    <a href="@Url.Action("Index", "Ad_UserTracking")" class="btn btn-primary"><i class="bx bx-rotate-right" style="margin: 0px 5px 0 0;"></i><span>Refresh</span></a>
                                </div>
                                <div class="col-md-6 text-end">
                                    <a href="@Url.Action("Index", "Ad_UserTracking")" class="btn btn-primary"><i class="las la-arrow-circle-left"></i><span>Back</span></a>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <link href="~/assets/libs/sweetalert2/sweetalert2.min.css" rel="stylesheet" type="text/css" />
    <script src="~/assets/libs/sweetalert2/sweetalert2.min.js"></script>

    <script>
        document.addEventListener("DOMContentLoaded",
            function () { new DataTable("#UserTracking", { scrollX: !0, sort: false }) })
    </script>
}