ProBillInvoice/Controllers/PartyMstCustLocationController.cs
using ProBillInvoice.DAL;
using ProBillInvoice.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProBillInvoice.Controllers
{
    [Authorize]
    public class PartyMstCustLocationController : Controller
    {
        // GET: PartyMstMustLocation
        public ActionResult Create()
        {
            ViewBag.Titlename = "Create";
            ClsPartyMaster lsPM = new ClsPartyMaster();
            ViewBag.PartyList = new SelectList(lsPM.PartyMaster_Categorywise("C"), "party_id", "party_name");
            ClsCityMaster lsCM = new ClsCityMaster();
            ViewBag.CityList = new SelectList(lsCM.Citymaster(), "city_id", "city_name");
            PartyMstCustLocationModel model = new PartyMstCustLocationModel();
            ClsPartyMstCustLocation lsPartyCust = new ClsPartyMstCustLocation();
            model.CustomerPartyList = lsPartyCust.CustomerPartymaster();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(PartyMstCustLocationModel model)
        {
            ViewBag.Titlename = "Create";
            ClsPartyMaster lsPM = new ClsPartyMaster();
            ViewBag.PartyList = new SelectList(lsPM.PartyMaster_Categorywise("C"), "party_id", "party_name");
            ClsCityMaster lsCM = new ClsCityMaster();
            ViewBag.CityList = new SelectList(lsCM.Citymaster(), "city_id", "city_name");
            ClsPartyMstCustLocation lsPartyCust = new ClsPartyMstCustLocation();
            if (model.id == 0)
            {
                model.Mode = 1;
                lsPartyCust.InsertUpdate(model);                
                ViewBag.Message = "Detail Save Sucessfully";
            }
            ModelState.Clear();
            PartyMstCustLocationModel mymodel = new PartyMstCustLocationModel();
            mymodel.CustomerPartyList = lsPartyCust.CustomerPartymaster();
            return View(mymodel);
        }

        public ActionResult Edit(int id)
        {
            ClsPartyMaster lsPM = new ClsPartyMaster();
            ViewBag.PartyList = new SelectList(lsPM.PartyMaster_Categorywise("C"), "party_id", "party_name");
            ClsCityMaster lsCM = new ClsCityMaster();
            ViewBag.CityList = new SelectList(lsCM.Citymaster(), "city_id", "city_name");

            ViewBag.Titlename = "Edit";
            ClsPartyMstCustLocation lsPartyCust = new ClsPartyMstCustLocation();
            PartyMstCustLocationModel CM = lsPartyCust.CustomerPartymaster(id);
            CM.CustomerPartyList = lsPartyCust.CustomerPartymaster();
            return View("Create", CM);
        }

        [HttpPost]
        public ActionResult Edit(PartyMstCustLocationModel CM)
        {
            ClsPartyMaster lsPM = new ClsPartyMaster();
            ViewBag.PartyList = new SelectList(lsPM.PartyMaster_Categorywise("C"), "party_id", "party_name");
            ClsCityMaster lsCM = new ClsCityMaster();
            ViewBag.CityList = new SelectList(lsCM.Citymaster(), "city_id", "city_name");

            ViewBag.Titlename = "Edit";
            ClsPartyMstCustLocation lsPartyCust = new ClsPartyMstCustLocation();
            if (CM.id != 0)
            {
                CM.Mode = 2;
                lsPartyCust.InsertUpdate(CM);
                
                ViewBag.Message = "Detail Save Sucessfully";
            }
            ModelState.Clear();
            PartyMstCustLocationModel mymodel = new PartyMstCustLocationModel();
            mymodel.CustomerPartyList = lsPartyCust.CustomerPartymaster();            
            return View("Create", mymodel);
        }
    }
}

ProBillInvoice/Views/PartyMstCustLocation/Create.cshtml
@model ProBillInvoice.Models.PartyMstCustLocationModel

@{
    ViewBag.Title = "Create";
    int SrNo = 0;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <div class="row">
        <div class="col-sm-5">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title mb-0 page-heading-color">Customer Site - @ViewBag.Titlename</h4>
                </div>

                <div class="card-body">
                    <div class="form-group">
                        <div>
                            @Html.HiddenFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.party_id, new { @class = "col-form-label", @style = "" })
                            </div>
                            <div class="col-md-9">
                                @Html.DropDownListFor(model => model.party_id, (SelectList)ViewBag.PartyList, "-- Select--", new { @class = "form-select", @style = "" })
                                @Html.ValidationMessageFor(model => model.party_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.location_id, new { @class = "col-form-label", @style = "" })
                            </div>
                            <div class="col-md-9">
                                @Html.DropDownListFor(model => model.location_id, (SelectList)ViewBag.CityList, "-- Select--", new { @class = "form-select", @style = "" })
                                @Html.ValidationMessageFor(model => model.location_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.location_detail, htmlAttributes: new { @class = "col-form-label" })
                                @Html.Label("*", htmlAttributes: new { style = "color: red;" })
                            </div>
                            <div class="col-md-9">
                                @Html.TextAreaFor(model => model.location_detail,2,8, new { @class = "form-control", @placeholder = "Enter Site location" } )
                                @Html.ValidationMessageFor(model => model.location_detail, "", new { @class = "text-danger" })

                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.defunct, htmlAttributes: new { @class = "col-form-label" })
                                @Html.Label("*", htmlAttributes: new { style = "color: red;" })
                            </div>
                            <div class="col-md-9">
                                <div class="checkbox" style="float: left; padding: 7px 10px 0px 0px;">
                                    @Html.EditorFor(model => model.defunct)
                                    @Html.ValidationMessageFor(model => model.defunct, "", new { @class = "text-danger" })
                                </div>
                                @Html.Label("Discontinue", htmlAttributes: new { @style = "float: left; padding: 5px 10px 0px 0px; margin-bottom: 0px; color: #b50a0a; width: 30%;" })
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12 text-end">
                                <button type="submit" class="save-btn-normal" title="Save"><i class="ri-save-line"></i>Save</button>
                                <button type="button" class="cancel-btn-normal" title="Cancel" id="btnSave" onclick="Refresh();"><i class="ri-close-fill"></i>Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-7">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0 page-heading-color">Customer Site</h5>
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="CustomerSite" class="table table-bordered dt-responsive nowrap table-striped align-middle app-tbl-one" style="width:100%">
                                <thead>
                                    <tr>
                                        <th style="text-align:center">Sr No</th>
                                        <th>@Html.DisplayNameFor(model => model.party_name)</th>
                                        <th>@Html.DisplayNameFor(model => model.city_name)</th>
                                        <th>@Html.DisplayNameFor(model => model.location_detail)</th>
                                        <th style="text-align:center">@Html.DisplayNameFor(model => model.defunct)</th>
                                        <th style="text-align:center">Action</th>
                                    </tr>
                                </thead>

                                @foreach (var item in Model.CustomerPartyList)
                                {
                                SrNo = SrNo + 1;
                                <tr>
                                    <td style="text-align: center;">@SrNo</td>
                                    <td><a href="#!">@Html.DisplayFor(modelItem => item.party_name)</a></td>
                                    <td>@Html.DisplayFor(modelItem => item.city_name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.location_detail)</td>
                                    @if (item.defunct == false)
                                    {
                                    <td style="text-align: center;"><i class="bi bi-check-circle" title="Active"></i> </td>
                                    }
                                    @if (item.defunct == true)
                                    {
                                    <td style="text-align: center;"><i class="ri-close-circle-line" title="Inactive"></i></td>
                                    }
                                    <td style="text-align: center;">
                                        <div class="dropdown d-inline-block">
                                            <button class="btn btn-soft-secondary btn-sm dropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                <i class="ri-more-fill align-middle"></i>
                                            </button>
                                            <ul class="dropdown-menu dropdown-menu-end mybtn2-form">
                                                <li><a href="@Url.Action(" Details","PartyMstCustLocation",new { id=item.id })" class="btn btn-info custom-toggle active"><i class="ri-eye-fill align-bottom"></i> View</a></li>
                                                <li><a href="@Url.Action(" Edit","PartyMstCustLocation",new { id=item.id })" class="btn btn-secondary custom-toggle"><i class="ri-pencil-fill align-bottom"></i> Edit</a></li>
                                                <li><a class="btn btn-danger custom-toggle" onclick="ConfirmDelete();"><i class="ri-delete-bin-fill"></i>Delete</a></li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                                }
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

}
@if (ViewBag.Message != null)
{
<script>
    window.onload = function () {

        Swal.fire({
            title: "<span style='color: #3085d6;'>@Html.Raw(ViewBag.Message)</span>",
            icon: "success",
            iconColor: "#04AA6D",
            confirmButtonClass: "w-xs me-2 mt-2",
            confirmButtonColor: "#3085d6",

        }).then((result) => {
            if (result.value) {
                window.location.href = "@Url.Action("Create", "PartyMstCustLocation")";
            }
        });
    };
</script>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    document.addEventListener("DOMContentLoaded",
        function () { new DataTable("#CustomerSite", { scrollX: !0, pageLength: 15, sort: !0 }) })
</script>

<script>
    function Refresh() {
        window.location.href = "@Url.Action("Create", "PartyMstCustLocation")";
    }
</script>
}