ProBillInvoice/Controllers/MaterialMasterController.cs
using ProBillInvoice.DAL;
using ProBillInvoice.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProBillInvoice.Controllers
{
    [Authorize]
    public class MaterialMasterController : Controller
    {
        public ActionResult Index()
        {
            ClsMaterialMaster MM = new ClsMaterialMaster();
            MaterialMasterModel Material = new MaterialMasterModel();
            Material.MaterialMasterList = MM.MaterialMasterList("Purchase");
            return View(Material);
        }

        public ActionResult Create()
        {
            ViewBag.Titlename = "Create";
            ClsGroupMaster lsGM = new ClsGroupMaster();
            ViewBag.GroupMaster = new SelectList(lsGM.GroupMaster_Groupwise("group_code in('02','01')"), "group_code", "long_desc");          
            ClsSubGroupMaster lsSGM = new ClsSubGroupMaster();
            ViewBag.SubGroupMaster = new SelectList(lsSGM.SubGroupMaster(), "sub_group_code", "long_desc");
            ClsSubSubGroupMaster lsSSGM = new ClsSubSubGroupMaster();
            ViewBag.SubSubGroupMaster = new SelectList(lsSSGM.SubSubGroupMaster(), "sub_sub_group_code", "long_desc");

            ClsUnitMaster lsUnit = new ClsUnitMaster();
            ViewBag.UnitList = new SelectList(lsUnit.UOMMaster(), "unit_code", "long_desc");            
            ViewBag.AltUnitList = new SelectList(lsUnit.UOMMaster(), "unit_code", "long_desc");

            MaterialMasterModel Material = new MaterialMasterModel();
            ClsMaterialMaster MM = new ClsMaterialMaster();
            Material.material_id = MM.NextId();
            Material.material_code = "*";
            Material.MaterialMasterList = MM.MaterialMaster_Type("Purchase");             
            return View(Material);
        }        

        public ActionResult Edit(int id)
        {
            ViewBag.Titlename = "Edit";
            ClsGroupMaster lsGM = new ClsGroupMaster();
            ViewBag.GroupMaster = new SelectList(lsGM.GroupMaster_Groupwise("group_code in('02','01')"), "group_code", "long_desc");
            ClsSubGroupMaster lsSGM = new ClsSubGroupMaster();
            ViewBag.SubGroupMaster = new SelectList(lsSGM.SubGroupMaster(), "sub_group_code", "long_desc");                        
            ClsSubSubGroupMaster lsSSGM = new ClsSubSubGroupMaster();
            ViewBag.SubSubGroupMaster = new SelectList(lsSSGM.SubSubGroupMaster(), "sub_sub_group_code", "long_desc");

            ClsUnitMaster lsUnit = new ClsUnitMaster();
            ViewBag.UnitList = new SelectList(lsUnit.UOMMaster(), "unit_code", "long_desc");
            ViewBag.AltUnitList = new SelectList(lsUnit.UOMMaster(), "unit_code", "long_desc");

            ClsMaterialMaster MM = new ClsMaterialMaster();
            MaterialMasterModel Material = MM.MaterialMaster(id);            
            Material.MaterialMasterList = MM.MaterialMaster_Type("Purchase");            
            return View("Create", Material);
        }
                
        public ActionResult Details(int id)
        {
            ClsMaterialMaster MM = new ClsMaterialMaster();
            MaterialMasterModel Material = MM.MaterialMaster(id);
            return View(Material);
        }

        [HttpPost]
        public ActionResult Create(MaterialMasterModel Material)
        {
            int SiteId = Convert.ToInt32(Session["LoginSiteId"].ToString());
            ClsMaterialMaster lsMM = new ClsMaterialMaster();
            if (Material.material_id != 0)
            {
                Material.Mode = 1;
                Material.material_type = "Purchase";
                Material.created_by = (string)Session["LoginUserName"];
                Material.created_date = DateTime.Now;

                lsMM.InsertUpdate(Material);
                ClsStStockHeader lsStStockHeader = new ClsStStockHeader();
                StStockHeaderModel stStockHeader = new StStockHeaderModel();
                ClsSiteMaster lsSiteMaster = new ClsSiteMaster();
                List<SiteMasterModel> SiteModel = lsSiteMaster.SiteMasterList();
                foreach (var item in SiteModel)
                {
                    stStockHeader.Mode = 1;
                    stStockHeader.material_id = Material.material_id;
                    stStockHeader.unit_code = Material.unit_code;
                    stStockHeader.site_id = item.site_id;
                    stStockHeader.created_by = (string)Session["LoginUserName"];
                    stStockHeader.created_date = DateTime.Now;
                    lsStStockHeader.InsertUpdate(stStockHeader);
                }
                ViewBag.Message += "Detail saved successfully."+ Environment.NewLine + "Please make stock posting before use in transaction.";
            }

            ModelState.Clear();            
            ClsGroupMaster lsGM = new ClsGroupMaster();
            ViewBag.GroupMaster = new SelectList(lsGM.GroupMaster(), "group_code", "long_desc");

            ClsSubGroupMaster lsSGM = new ClsSubGroupMaster();
            ViewBag.SubGroupMaster = new SelectList(lsSGM.SubGroupMaster(), "sub_group_code", "long_desc");

            ClsSubSubGroupMaster lsSSGM = new ClsSubSubGroupMaster();
            ViewBag.SubSubGroupMaster = new SelectList(lsSSGM.SubSubGroupMaster(), "sub_sub_group_code", "long_desc");

            ClsUnitMaster lsUnit = new ClsUnitMaster();
            ViewBag.UnitList = new SelectList(lsUnit.UOMMaster(), "unit_code", "long_desc");
            ViewBag.AltUnitList = new SelectList(lsUnit.UOMMaster(), "unit_code", "long_desc");

            MaterialMasterModel model = new MaterialMasterModel();
            model.MaterialMasterList = lsMM.MaterialMaster_Type("Purchase");
            ViewBag.Titlename = "Create";
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(MaterialMasterModel Material)
        {            
            ClsMaterialMaster lsMM = new ClsMaterialMaster();
            if (Material.material_id != 0)
            {
                Material.Mode = 2;
                Material.material_type = "Purchase";
                Material.last_edited_by = "ADMIN";
                Material.last_edited_date = DateTime.Now;
                lsMM.InsertUpdate(Material);
                ViewBag.Message = "Detail saved successfully";
            }
            ModelState.Clear();

            ClsGroupMaster lsGM = new ClsGroupMaster();
            ViewBag.GroupMaster = new SelectList(lsGM.GroupMaster(), "group_code", "long_desc");

            ClsSubGroupMaster lsSGM = new ClsSubGroupMaster();
            ViewBag.SubGroupMaster = new SelectList(lsSGM.SubGroupMaster(), "sub_group_code", "long_desc");

            ClsSubSubGroupMaster lsSSGM = new ClsSubSubGroupMaster();
            ViewBag.SubSubGroupMaster = new SelectList(lsSSGM.SubSubGroupMaster(), "sub_sub_group_code", "long_desc");

            ClsUnitMaster lsUnit = new ClsUnitMaster();
            ViewBag.UnitList = new SelectList(lsUnit.UOMMaster(), "unit_code", "long_desc");
            ViewBag.AltUnitList = new SelectList(lsUnit.UOMMaster(), "unit_code", "long_desc");

            MaterialMasterModel model = new MaterialMasterModel();
            model.MaterialMasterList = lsMM.MaterialMaster_Type("Purchase"); 

            ViewBag.Titlename = "Edit";
            return View("Create", model);
        }

        //------------------------------------------
        public JsonResult FillByGroupCode(string GroupCode, string GroupName)
        {
            ClsSubGroupMaster lsSGM = new ClsSubGroupMaster();
            List<SubGroupMasterModel> SubGroupMaster = new List<SubGroupMasterModel>();
            SubGroupMaster = lsSGM.FillByGroupCode(GroupCode);
            var result = new { List = new SelectList(SubGroupMaster, "sub_group_code", "long_desc") };
            return Json(result);
        }

        public JsonResult FillBySubGroupCode(string SubGroupCode, string SubGroupName)
        {
            ClsSubSubGroupMaster lsSGM = new ClsSubSubGroupMaster();
            List<SubSubGroupMasterModel> SubSubGroupMaster = new List<SubSubGroupMasterModel>();
            SubSubGroupMaster = lsSGM.FillBySubGroupMaster(SubGroupCode);
            var result = new { List = new SelectList(SubSubGroupMaster, "sub_sub_group_code", "long_desc") };
            return Json(result);
        }

        public ActionResult NextItemCode(string SubSubGroupCode, string SubSubGroupName)
        {
            ClsMaterialMaster lsIM = new ClsMaterialMaster();
            string ItemCode = lsIM.NextItemCode(SubSubGroupCode);

            try
            {
                return Json(new
                {
                    msg = ItemCode
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult UnitCode(int id, string name)
        {
            ClsUnitMaster lsUnit = new ClsUnitMaster();
            UnitMasterModel UM = new UnitMasterModel();
            UM = lsUnit.UOMMaster(id);
            var result = new { UM.short_desc };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

ProBillInvoice/Views/MaterialMaster/Details.cshtml
@model ProBillInvoice.Models.MaterialMasterModel

@{
    ViewBag.Title = "Details";
}

<div class="form-horizontal">
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-sm-6">
                            <h5 class="card-title mb-0 page-heading-color">Material Master - Details</h5>
                        </div>
                        <div class="col-sm-6" style="text-align: right;">
                            <a href="@Url.Action("Create", "MaterialMaster")" class="back-btn"><i class="las la-arrow-circle-left"></i>Back</a>                            
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <div class="form-group" style="margin-bottom:0px;">
                        <div class="row mb-3">
                            <div class="col-md-12">
                                @Html.HiddenFor(model => model.material_id, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.material_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-sm-3">
                                @Html.LabelFor(model => model.material_name, htmlAttributes: new { @class = "form-label", @style = "font-weight: bold;" })
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.material_name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.material_name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-sm-3">
                                @Html.LabelFor(model => model.material_recipe_name, htmlAttributes: new { @class = "form-label", @style = "font-weight: bold;" })
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.material_recipe_name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.material_recipe_name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-sm-3">
                                @Html.LabelFor(model => model.material_type, htmlAttributes: new { @class = "form-label", @style = "font-weight: bold;" })
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.material_type, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.material_type, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="row mb-3">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.opening_quantity, htmlAttributes: new { @class = "form-label", @style = "font-weight: bold;" })
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.opening_quantity, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.opening_quantity, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                        <div class="row mb-3">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.material_rate, htmlAttributes: new { @class = "form-label", @style = "font-weight: bold;" })
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.material_rate, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.material_rate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProBillInvoice/Views/MaterialMaster/Index.cshtml
@model RMCWeb.Models.MaterialMasterModel

@{
    ViewBag.Title = "Index";
    int SrNo = 0;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-sm-6">
                            <h5 class="card-title mb-0 page-heading-color">List of Material</h5>
                        </div>
                        <div class="col-sm-6" style="text-align: right;">
                            <a href="@Url.Action("Create", "MaterialMaster")" class="back-btn"><i class="las la-arrow-circle-left"></i>Back</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="MaterialMaster" class="table table-bordered dt-responsive nowrap table-striped align-middle app-tbl-one" style="width:100%">
                                <thead>
                                    <tr>
                                        <th scope="col" style="text-align: center;">Sr No</th>
                                        <th>@Html.DisplayNameFor(model => model.gr_name)</th>
                                        <th>@Html.DisplayNameFor(model => model.sub_gr_name)</th>
                                        <th>@Html.DisplayNameFor(model => model.sub_sub_gr_name)</th>
                                        <th scope="col">@Html.DisplayNameFor(model => model.material_code)</th>
                                        <th scope="col">@Html.DisplayNameFor(model => model.material_name)</th>
                                        <th scope="col">@Html.DisplayNameFor(model => model.material_recipe_name)</th>                                        
                                    </tr>
                                </thead>

                                @foreach (var item in Model.MaterialMasterList)
                                {
                                SrNo = SrNo + 1;
                                <tr>
                                    <td style="text-align: center;">@SrNo</td>
                                    <td>@Html.DisplayFor(modelItem => item.gr_name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.sub_gr_name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.sub_sub_gr_name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.material_code)</td>
                                    <td><a href="#!">@Html.DisplayFor(modelItem => item.material_name)</a></td>
                                    <td style="color: darkgray;">@Html.DisplayFor(modelItem => item.material_recipe_name)</td>                                    
                                </tr>
                                }
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    document.addEventListener("DOMContentLoaded",
        function () { new DataTable("#MaterialMaster", { scrollX: !0, sort: !0  }) })
</script>

<script>
    function Refresh() {
        window.location.href = "@Url.Action("Create", "MaterialMaster")";
    }
</script>
}